index.html

#2 navbar fixed

---

index.html

Fixes #2 
I aligned the navbar, added the new toggle theme switch and aligned the translate button as well
- [X ] Bug fix

#2 - navbar aligned and translate button fixed

---

about.html
resume.html
styles.css

#20 I have added CSS in the ABOUT US PAGE and MY RESUME PAGE
@Ojas-Arora

Fixes the issue in ABout and Resume Page

---

about.html
index.html
resume.html
styles.css

Reverts Ojas-Arora/SCD-Profile-Score#17

Revert "Fix/remove begin your journey"

---

index.html

#37 add Top scroll button Issue fixed , Add SWOC labels to this PR , @Ojas-Arora                                                                                     ScreenRecording :                                                                                                                        
https://github.com/user-attachments/assets/80c6e515-e1dd-4723-8700-bf85e24d3109

#37 Top Scroll button Fixed

---

index.html

Fixes #1 
Fixed the footer Conflicts and branch conflicts 
> **Before**
> **After**

Fixed Conflicts and added footer

---

index.html

Fixes https://github.com/Ojas-Arora/SCD-Profile-Score/issues/32
I have added CSS to enhance the UI of the card.
@Ojas-Arora  pls add give pts for this and add suitable labels

Improves UI of Home page Card

---

about.css
index.html
navbar.css

#55 Resolved
Add Desired CSS and improves the UI of about us page.
@Ojas-Arora  pls add suitable labels and give pts for this PR

Fixes Need Improvement in About us page

---

contact.html

Fixes #53 
I have validated the "Name" field of the contact form so that the user cannot enter gibberish values like only numbers or special symbols etc.
Now an error raises and does not allow user to submit the form until he fills in the proper name in the "Name" field

fixed validation of name field in contact form via a new branch

---

index.html
index.js

#57  Added Animation in Navbar
@Ojas-Arora pls check and merge

Fixed Added Animation in Navbar

---

faq.html
index.html

#58  Resolved the issues in landing page
@Ojas-Arora pls add labels and merge

Fixed Issues in footer of landing page, FAQ's Page 

---

.hintrc
index.html
styles.css

#69 give responsiveness to the entire landing page.
@Ojas-Arora pls add suitable labels and merge

Fixed Issues in Responsiveness of landing page

---

faq.html

Fixes #64 
Added functionality for switching between dark and light modes.
Enhanced styling and UI improvements.
Added extra questions for clarity. 
Improved overall user experience.
https://github.com/user-attachments/assets/58de1aa2-915a-4203-81b4-9ae496978cf3
Hey @Ojas-Arora, please review the changes. If everything looks good, kindly merge this pull request. Also, I would appreciate it if you could provide my score on https://os-lead.vercel.app/. Thank you!

Faq page layout improved

---

login.css
login.html
register.css
register.html

Fixes #92 
Added back button to go back from login and register pages.
- [✅] Bug fix
- [✅] I have performed a self-review of my code
- [✅] I have read and followed the Contribution Guidelines.
- [✅] I have tested the changes thoroughly before submitting this pull request.
- [✅] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [✅] I have commented my code, particularly in hard-to-understand areas.

added back button for login and register pages.

---

register.css
register.html

Fixes #105 
Confirm Password Added
##

Added Confirm Password

---

contributors/contributor.html
index.html
testimonial.css
testimonial.html

#121 - Testimonial page

---

index.html
privacy.css
privacy.html

fixed Privacy Policy page to the website , Add SWOC Labels to the PR  and level to this PR  @Ojas-Arora 
Screenrecording :
https://github.com/user-attachments/assets/5dda66a5-db23-48d0-8327-ab08d85da07a

Fixed Privacy Policy

---

contact.css
contact.html

Fixes #120 
Resolved the alignment issues of the footer section on the contact page to ensure proper layout and consistency across the webpage. The footer is now responsive, visually appealing, and well-integrated with the overall design.
---
---
This PR resolves the footer alignment issue on the contact page. The changes ensure the footer remains consistent across different screen sizes and aligns properly with the page content. Screenshots showcasing the fixed footer have been attached for reference.

updating the footer section in the contact page

---

about.css
about.html

Fixes #114 
I have made the UI of about us cards slightly better by improving some color combo and styles.

Improved About UI

---

index.html
resume.css
resume.html
styles.css

Fixes #46
added footer in resume same as exists in home sectio

Resume footer

---

terms.css
terms.html

Fixed Terms and Conditions page to the Website , As This Page matches the theme of the Website , Add SWOC labels to this PR @Ojas-Arora 
Screenrecording :
Uploading Screen Recording 2025-01-16 181504.mp4…

Add Terms and Conditions Page

---

about.css
about.html

Fixes #132
Made ui of about us section aligned with website ui
- [✅ ] Bug fix
- [✅ ] I have performed a self-review of my code
- [✅ ] I have read and followed the Contribution Guidelines.
- [✅ ] I have tested the changes thoroughly before submitting this pull request.
- [✅ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.

about section ui

---

contributors/contributor.css
contributors/contributor.js

Added style to contributors page

---

contributors/contributor.css
contributors/contributor.html

Added CSS to make dark mode working in contributor page

---

blog.css
blog.html
blog1.html
blog2.html
blog3.html

Fixes #133 
I have added blog pages  which contains 3 blogs and when read mode button is clicked it will show full blog.
- [✅ ] Bug fix
- [✅ ] I have performed a self-review of my code
- [✅ ] I have read and followed the Contribution Guidelines.
- [✅ ] I have tested the changes thoroughly before submitting this pull request.
- [✅ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.

Added blog page

---

index.html

This pull request addresses issue #103 by enhancing the home page design for improved user experience and visual appeal. The changes include updates to the carousel and cards, aligning them with modern UI/UX practices.  
---
Fixes #103  
---
https://github.com/user-attachments/assets/fe58e5ef-b64d-46ab-9899-4db5c09bfec7
---
- Smooth transitions and animations for slides.  
- Added indicators for slide progression (dots/progress bar).  
- Improved responsiveness across devices (desktop, tablet, mobile).  
- Navigation controls (arrows/swipe gestures) for better interactivity.  
- Modern styles: shadows, rounded corners, and gradients.  
- Enhanced typography for better readability.  
- Interactive hover effects (scaling, color changes, button animations).  
- Icons and tags for better …

Home page UI

---

register.css

Fixes #143 
In this update, I've enhanced the **Sign-Up button** with smooth and engaging hover effects to create a more interactive user experience. 💻✨  
- **Hover Effect:** The button now grows slightly  on hover, making it feel dynamic and responsive. 📈  
- **Color Transition:** The background smoothly transitions from dark red to a vibrant orange, giving users visual feedback on their action. 🔥  
- **Box Shadow:** Added a subtle box-shadow around the button on hover, adding depth and highlighting the button further. 🌟  
- **Active Effect:** On click, the button slightly shrinks  to provide a satisfying feedback, ensuring users feel their action. 🤏
These enhancements improve the user interface and make the Sign-Up page more interactive, ensuring users have a seamless experience! 😊
--- …

✨ Added Engaging Hover Effects to the Sign-Up Button for Better User Interaction! 🎉

---

about.css
about.html

**Fixes #149** 
🎉 Excited to share a new feature update!  
📍 **What’s New?**  
I’ve implemented a smooth **scroll-to-top button** on the **About Page**, making navigation more user-friendly and visually engaging.  
💡 **Highlights:**  
- 🖌️ Enhanced user experience with smooth scrolling.  
- 🔥 Stylish button design for improved aesthetics.  
- 🚀 Boosted page accessibility and convenience.  
This small addition ensures a seamless browsing experience for users, especially on lengthy pages. 🌟  
---
---
---
---
Added a scroll-to-top button on the **About Page**, enhancing user experience and accessibility. Screenshots and a demo video have been included for better understanding and review.

🚀✨ Added a Scroll Button to the About Page!

---

about.css
about.html
blog.html
contact.html
index.html
navbar.css
pricing.html
privacy.html
resume.html
terms.html
testimonial.html

Fixes #147 
When customers visit a website to purchase different pro plans, they expect to see clear information about payment options. If this information is missing, especially in the footer, it can lead to confusion and doubts about available payment methods. This uncertainty might discourage customers from completing their purchase.

adding payment options #147

---

pricing.css
pricing.html

Fixes #159
🔹 **What's New?**  
I have successfully added a **scroll button** 🖱️ to the **Pricing Page** of the project! This new feature enhances user navigation and provides a seamless experience by allowing users to quickly return to the top of the page.  
🔹 **Highlights**:  
✅ Smooth scroll animation for better aesthetics 🎥.  
✅ Responsive design for all devices 📱💻.  
✅ Intuitive placement to ensure easy accessibility 👌.  
🔹 **Why It Matters?**  
Adding a scroll button improves **usability** and keeps the page looking professional and user-friendly 🌟.  
Looking forward to hearing your thoughts! 💬 Your feedback means a lot 🙌.  
---
---
- 🖱️ **Scroll Button Feature**: This addition enhances the Pricing Page by providing smooth navigation and better user experience.  
- 📹 Screenshots …

🎉✨ Title: Enhanced the Pricing Page with a Scroll Button 🚀💻

---

contributors/contributor.css
contributors/contributor.js

Hey @Ojas-Arora ,
Could you please review and merge this PR under SWOC?
As per your feedback, I have made the requested changes to the previous PR. Please review and let me know if any further updates are needed. 😊
Generate Certificate for Contributors , where Users can generate and download their Certificate , This is now accessible to their github Profiles
Screenrecording : 
https://github.com/user-attachments/assets/7900ae73-f9eb-4b9c-a58f-1f7e7ea83cc8
https://github.com/user-attachments/assets/cedd8649-c347-4855-9a7c-271366ac2a58

Certificate for Contributors

---

contact.css

Fixes #155 
Enhanced Ui in dark mode of contact page.
- [✅ ] Feature enhancement
- [ ✅ ] I have performed a self-review of my code
- [ ✅ ] I have read and followed the Contribution Guidelines.
- [ ✅ ] I have tested the changes thoroughly before submitting this pull request.
- [ ✅ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ✅ ] I have commented my code, particularly in hard-to-understand areas.

enhanced Ui of contact page

---

testimonial.css
testimonial.html

Hey @Ojas-Arora ,
Could you Please review and let me know if any further updates are needed and merge this PR under SWOC. 😊
I updated the Branch and then create this new PR .
Screenrecording : 
https://github.com/user-attachments/assets/861263e1-6f39-4813-9404-987c23dbd534

Fixed Testimonial Page

---

contact.css
pricing.css

Fixes #166
🎉 **Update Alert!** 🎉  
I’ve successfully enhanced the **hovering effects** on the **Contact Page** of my project! 🖥️💻 Here's what I did in detail:  
✅ **Improved User Experience (UX):**  
- Added smooth hover transitions for all interactive elements, ensuring a polished and professional feel. 🪄  
- Enhanced button hover effects with a subtle color transition to make actions more intuitive and visually engaging. 🎨✨  
✅ **Focus on Design Consistency:**  
- Ensured the hovering effects match the overall theme of the project, maintaining a cohesive design language. 🎯  
- Carefully tested responsiveness across devices, from mobile 📱 to desktop 🖥️.  
✅ **Technical Details:**  
- Used **CSS transitions and keyframes** to create visually appealing effects. 🎥  
- Optimized the …

✨ Fixed Hovering Effects on Contact Page 🚀

---

about.css
about.html
blog.css
blog.html
contact.css
contact.html
contact.js
contributors/contributor.css
contributors/contributor.html
faq.html
login.html
navbar.css
pricing.css
pricing.html
register.html
resume.css
resume.html
terms.html

#82 Added feature in the issue.
@Ojas-Arora merge and give pts.

Added cursor animation to the different pages. 

---

about.css
about.html
blog.html
contact.css
contact.html
contact.js
contributors/contributor.html
faq.html
pricing.css
pricing.html
terms.html

#81 Added feature described issue 
@Ojas-Arora merge and give pts.

added Animation in navbar for Different Pages.

---

about.css
about.html
blog.css
blog.html
contact.css
contact.html
contact.js
contributors/contributor.css
contributors/contributor.html
faq.html
index.html
login.html
navbar.css
pricing.css
pricing.html
register.html
resume.css
resume.html
styles.css
terms.html

#167 Resolved issues which is described
@Ojas-Arora merge and give pts.

Fixed Issues in Footer of Landing Page and Navbar

---

about.css
about.html

Fixes #197
🚀 **Enhancement Overview**:  
I have successfully added a **scroll-to-top button** on the **About Page**, improving the user experience by enabling smooth and quick navigation to the top of the page.  
🛠️ **Details of Changes**:  
- Designed and implemented a visually appealing scroll button.  
- Added smooth scrolling functionality for a seamless user experience.  
- Ensured the button is responsive and works well on different screen sizes.  
- Verified consistent styling with the overall theme of the page.  
🔍 **Testing**:  
- The scroll button was tested across multiple browsers and devices to ensure functionality and responsiveness.  
- Verified compatibility with other elements on the page, ensuring no layout distortion.  
📌 **Impact**:  
This update enhances usability and …

✨ Added Scroll Button to About Page ✨

---

pricing.css

Fixes #193 
Improved the visiblility of text on the 'Choose Plan' buttons in both light  mode and dark mode.
I have also adjusted the positioning of the buttons to make UI better.
**Before:**
**After:**

improved looks of button on the 'go pro' section

---

index.html
index.js

Added Feature described in #182
@Ojas-Arora merge and give pts

Added GSAP Scroll Animation

---

styles.css

Added UI for the Scrollbar for all pages !!!

---

contributors/contributor.css
index.html
index2.html
navbar.css
pricing.css
resume.css
resume.html

Add toggle index2

---

.gitignore
Server/api/app.js
Server/api/dbconnect.js
Server/controller/contactController.js
Server/routes/contactRoutes.js
contact.html
package-lock.json
package.json

Dynamic contact us(email) functionality

---

contact.html
faq.html
login.html
pricing.css

Fix dark mode in FAQ page

---

index2.html

Fixed back button conflicts in index2 page

---

faq.html
index2.html

Actually not missing but fixed mis matched back button in FAQ page

---

testimonial.css
testimonial.html

Added Back button in Testimonial page

---

contributors/contributor.css
contributors/contributor.html

Add back button contributors

---

blog.css
blog.html

Add back button in blog page

---

blog.css
blog.html

Created Blog page responsive

---

contributors/contributor.css

Fixed navbar color conflict"

---

contributors/contributor.css
login.html
register.html

Fix eye icon in login page 

---

contributors/contributor.js

Fixes #248 
I have added github icon for github profile link 
https://github.com/user-attachments/assets/48b28fc5-0da7-414a-ba35-d8b6bf25e17e

Added github icon

---

about.html
blog.html
contact.html
contributors/contributor.html
faq.html
index.html
index2.html
login.html
pricing.html
privacy.html
register.html
resume.html
terms.html
testimonial.html

Redirect to home page onclick of Ajivika's logo

---

js/login.js
login.html

Fixes #51 
I have added complete login backend so that user can login successfully.

Login Backend Implemented Successfully

---

contributors/contributor.js

Fixes #264
I have changed the content of the certificate so that it will applicable for all contributors and added underline in the below of signature

changed contributor certificate

---

about.css
contact.css
pricing.css

Fix back button in Pricing, Contact, About page

---

terms.css
terms.html

Fix footer text in terms and condition page

---

index.html

Fixes #184
This PR introduces the **Ajivika AI Chatbot**, designed to assist users with **resume building, smart job recommendations, and course suggestions** for career growth. It includes chatbot UI integration, an AI-driven job matching system, and a resume feedback mechanism.

🚀 Integrating AI-Powered Chatbot for Job & Career Assistance

---

testimonial.html

…roll to top button confliction
Fixes #278 

Added dynamic count of reviews in testimonials page 

---

contact.css
contact.html

Added tooltips

---

terms.css
terms.html

Fixes #218
Improved UI in terms and conditions page.

improved ui of terms page

---

login.css
register.css

Resolved issue described in #250 
@Ojas-Arora merge and give pts

Added Background Color Theme of Register and Login Page

---

index2.html
style2.css

closes #232 
Jobs cards will be displayed according to user's search.

added job cards with responsiveness

---

about.html
chatbot.html
contact.html
contributors/contributor.html
index.html
pricing.html
privacy.html
terms.html
testimonial.html

Fixed- Floating Button in all page 

---

about.html
blog.html
contact.html
contributors/contributor.html
cssfiles/Scroll.css
faq.html
index.html
js/Scroll.js
pricing.html
privacy.html
terms.html
testimonial.html

Fixes  #307
This PR introduces an animated scroll-to-top button that will be available on all pages of the website. The button becomes visible when the user scrolls down and smoothly scrolls the page back to the top when clicked. This feature enhances user navigation and overall experience.

Add Animated Scroll-to-Top Button Across All Pages

---

Server/api/app.js
Server/controller/authController.js
Server/middleware/auth.middleware.js
Server/middleware/authMiddleware.js
Server/middleware/upload.js
Server/models/User.js
Server/routes/userRoutes.js
js/login.js
package-lock.json
profile.html
profile.js

Fixes #311 
@Ojas-Arora I have added backend to profile page so that after an user gets logged in it will be redirected to the profile page which will fetch  necessary details that user has provided during signup.Username field cannot be edited as everyone should have unique username but any other fields present in the profile page  can  be edited. Another thing that i will do in the next issue i had raised is that to improve the styling of the logout option which is already present here. kindly review it and merge it.

Added backend to profile page

---

README.md

Hi @Ojas-Arora,
Fixes #316 
This pull request updates the project structure section in the README.md file to reflect the current directory structure of the project. The updated structure provides a clear and detailed overview of the project's organization, making it easier for contributors to navigate and understand the project layout.
- Existing structure to match the current state of the project.

Update Project Structure in README.md

---

resume.css
resume.html

Fixes #274 
Previously , when an user didn't add anything to the fields to the form then also the resume gets downloaded blank. So in this issue i have added input validation so that that resume gets downloaded when user fills atleast the details in the fields which are starmarked . @Ojas-Arora please review it and merge it when you get time as soon as possible.

Added Input Validation to Resume

---

profile.css
profile.html

Fixes #314 
As I wrongly pushed the code  the login and logout functionality in the previous issue of  profile page backend. So Here I improved the styling of logout button and also solved the issue of hamburger of navbar in profile page not showing in the mobile view. @Ojas-Arora Please review it and merge it as soon as possible.

Improving styling of logout button

---

Server/config/cloudinary.js
Server/middleware/upload1.js
Server/models/User.js
Server/routes/userRoutes.js
package-lock.json
package.json
profile.js

Fixes #317 
I have added backend to profile image using cloudinary with credentials present in .env file. @Ojas-Arora kindly review it and merge it.

Added profile image backend using cloudinary

---

navbar.css

#326 Resolved issue described 
@Ojas-Arora merge and give pts

Fixed Issue of Navbar responsiveness

---

login.css

Fixes #338 
Implemented responsive login page in mobile view.

Responsive login page design in mobile view

---

register.css
register.html

Fixes #337 
Implemented Responsive Register page in mobile view. @Ojas-Arora kindly review it and merge it.

Responsive register page in mobile view

---

terms.css
terms.html

Fixes #339 
Made terms responsive in mobile view. @Ojas-Arora Please review it and merge it.

Made terms responsive in mobile view

---

blog.css
blog.html
contact.html
faq.html
login.html
privacy.css
privacy.html
register.html
resume.css
resume.html
terms.css
terms.html
testimonial.html

Fixes #354 
Updated the Twitter icon to X across the project to reflect the latest rebranding. This ensures consistency and alignment with the platform's new identity.
This update ensures the project stays up to date with Twitter's rebranding to X, maintaining a modern and accurate user experience.

Updated twitter icon to X

---

index.html
styles.css

Fixes #321 
I changed the front ui of cards present in home page

home page cards

---

contact.html
contributors/contributor.css
contributors/contributor.html
pricing.html
privacy.html
terms.html
testimonial.html

Fixes #254 
Added Footer . @Ojas-Arora Kindly review it and merge it and also provide me points of previously merged pull requests ,I think you have forgotten to give points.

Added Footer to all the pages
